---
- name: Setup Minikube
  hosts: all
  become: true
  tasks:
    - name: Update system
      apt:
        update_cache: yes

    - name: Upgrade system
      apt:
        upgrade: dist

    - name: Install Dependencies
      shell: "sudo apt install -y curl wget apt-transport-https"
      args:
        executable: /bin/bash

    - name: Download Minikube Binary
      shell: |
              wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
              sudo cp minikube-linux-amd64 /usr/local/bin/minikube
              sudo chmod +x /usr/local/bin/minikube

      args:
        executable: /bin/bash
        
    - name: Install Kubectl
      shell: |
              curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
              chmod +x kubectl
              sudo mv kubectl /usr/local/bin
      
      args:
        executable: /bin/bash
        
    - name: Start minikube on docker
      shell: "minikube start --driver=docker"
      args:
        executable: /bin/bash